# This is an azure pipeline that can be used to run E2E api tests using karate scripts
trigger: none
pr: none

parameters:
  - name: environment
    displayName: Environment
    type: string
    values:
      - dev
      - staging
      - preprod
      - staging
      - preprod
    default: dev
  - name: tag
    displayName: tag
    type: string
    values:
      - zpu
      - bbc
      - profile
    default: notification
resources:
  repositories:
    - repository: api-tests-mc
      type: github
      endpoint: github
      name: ab/api-tests-mc
      ref: master
variables:
  - group: DD_PATS
  - name: CD_DC_CIRCLECI_IMAGE
    value: ba/cd-cd:circleci-2.3.2
pool:
  name: agent-ec2-dev-uk

stages:
  - stage: ExecuteKarateTests
    displayName: "Notification Test Execution"
    jobs:
      - template: /azure-yaml/templates/jobs/vr_image.yml@cd-workflows
        parameters:
          REPO_RESOURCE: cd-workflows
      - job: ExecuteKarateTests
        dependsOn: resolve_cd_workflows_image
        timeoutInMinutes: 240
        steps:
          - bash: |
              docker run --rm \
                -v "$(pwd):/home/gradle" \
                -u 1000:1000 \
                --entrypoint /bin/bash gradle:7.4.1-jdk8 \
                -c './gradlew clean test -Denv=${{parameters.environment}} -Doptions="--tags ${{parameters.tag}}"'
              TEST_EXIT_CODE=$?
              sudo chown -R ubuntu:ubuntu .
              if test ${TEST_EXIT_CODE} -ne 0 ; then
                exit 1
              fi
          - task: PublishPipelineArtifact@1
            displayName: Publish Test Report
            inputs:
              artifactName: 'api test report'
              targetPath: '$(Pipeline.Workspace)/s/target/cucumber-html-reports'
              artifact: Report
            condition: succeededOrFailed()
